In [1]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [2]:
! pip install numpy pandas

Collecting numpy
  Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 330.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 463.4 kB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.1.4-cp310-cp310-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\4005\anaconda3\envs\lambda3_10\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\4005\anaconda3\envs\lambda3_10\lib\site-packages (from pandas) (2023.3.post1)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ---------------------------------------- 0.0/341.8 kB ? eta -:--:--
     ------- ------------------------------- 61.4/341.8 kB 1.7 MB/s eta 0:00:01
     ------------- ------------------------ 122.9/341.8 kB 1.4 MB/s eta 0:00:01
     --------------------- ---------------- 194.6/341.8 kB 1.5 MB/s eta 0:00:01
     --------------------------- ---------- 245.8/341.8 kB 1.4 MB/s eta 0:00:01
     --------------------------------- ---- 297.0/341.8 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 341.8/341.8 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\4005\anaconda3\envs\lambda3_10\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading numpy-1.26.2-cp310-cp310-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 2.3 MB/s eta 0:00:07
   ---------------------------------------- 0.1/15.8 MB 1.7 MB/s eta 0:00:10
   ---------------------------------------- 0.2/15.8 MB 1.3 MB/s eta 0:00:12
    --------------------------------------- 0.2/15.8 MB 1.3 MB/s eta 0:00:13
    --------------------------------------- 0.3/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.4/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.5/15.8 MB 1.5 MB/s eta 0:00:10
   - -------------------------------------- 0.6/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.6/15.8 MB 1.4 MB/s eta 0:00:11
   - -------------------------------------- 0.7/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.7/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.8/15.8 MB 1.4 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/15.8 MB 1.4 MB/s eta 0:00:11
   -- ------------------------------------- 0.9/15.8 MB 1.4 MB/s eta 0:00:11
   -- ------------------------------------- 0.9/15.8 MB 1.4 MB/s eta 0:00:11
   -- ------------------------------------- 1.0/15.8 MB 1.4 MB/s eta 0:00:11
   -- ------------------------------------- 1.1/15.8 MB 1.3 MB/s eta 0:00:12
   -- ------------------------------------- 1.1/15.8 MB 1.3 MB/s eta 0:00:12
   -- ------------------------------------- 1.2/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.2/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.4/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.4/15.8 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.4/15.8 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.5/15.8 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/15.8 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.6/15.8 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.7/15.8 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.7/15.8 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.8/15.8 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.9/15.8 MB 1.2 MB/s eta 0:00:12
   ---- ----------------------------------- 1.9/15.8 MB 1.2 MB/s eta 0:00:12
   ----- ---------------------------------- 2.0/15.8 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.0/15.8 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.1/15.8 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.2/15.8 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.2/15.8 MB 1.2 MB/s eta 0:00:12
   ----- ---------------------------------- 2.3/15.8 MB 1.2 MB/s eta 0:00:11
   ----- ---------------------------------- 2.3/15.8 MB 1.2 MB/s eta 0:00:11
   ------ --------------------------------- 2.4/15.8 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.5/15.8 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.6/15.8 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.7/15.8 MB 1.3 MB/s eta 0:00:11
   ------- -------------------------------- 2.8/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.0/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.0/15.8 MB 1.3 MB/s eta 0:00:10
   ------- -------------------------------- 3.1/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.2/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.2/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.3/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.4/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.4/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.5/15.8 MB 1.4 MB/s eta 0:00:10
   --------- ------------------------------ 3.6/15.8 MB 1.4 MB/s eta 0:00:10
   --------- ------------------------------ 3.6/15.8 MB 1.4 MB/s eta 0:00:09
   --------- ------------------------------ 3.7/15.8 MB 1.4 MB/s eta 0:00:09
   --------- ------------------------------ 3.7/15.8 MB 1.4 MB/s eta 0:00:09
   --------- ------------------------------ 3.8/15.8 MB 1.3 MB/s eta 0:00:09
   --------- ------------------------------ 3.9/15.8 MB 1.3 MB/s eta 0:00:09
   --------- ------------------------------ 3.9/15.8 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.0/15.8 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.0/15.8 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.1/15.8 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.2/15.8 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.2/15.8 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.3/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.4/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.4/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.5/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.6/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.6/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.7/15.8 MB 1.3 MB/s eta 0:00:09
   ------------ --------------------------- 4.8/15.8 MB 1.3 MB/s eta 0:00:09
   ------------ --------------------------- 4.8/15.8 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 5.0/15.8 MB 1.4 MB/s eta 0:00:08
   ------------ --------------------------- 5.0/15.8 MB 1.4 MB/s eta 0:00:08
   ------------ --------------------------- 5.1/15.8 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.2/15.8 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.3/15.8 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.3/15.8 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.3/15.8 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.3/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.4/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.4/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.6/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.7/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.7/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.7/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.7/15.8 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 5.7/15.8 MB 1.1 MB/s eta 0:00:09
   -------------- ------------------------- 5.8/15.8 MB 1.1 MB/s eta 0:00:09
   -------------- ------------------------- 5.8/15.8 MB 1.1 MB/s eta 0:00:09
   -------------- ------------------------- 5.8/15.8 MB 1.1 MB/s eta 0:00:09
   -------------- ------------------------- 5.8/15.8 MB 1.1 MB/s eta 0:00:10
   -------------- ------------------------- 5.8/15.8 MB 1.1 MB/s eta 0:00:10
   -------------- ------------------------- 5.9/15.8 MB 1.1 MB/s eta 0:00:10
   -------------- ------------------------- 5.9/15.8 MB 1.1 MB/s eta 0:00:10
   -------------- ------------------------- 5.9/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 5.9/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 6.0/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 6.0/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 6.0/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 6.1/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 6.1/15.8 MB 1.1 MB/s eta 0:00:10
   --------------- ------------------------ 6.2/15.8 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 6.3/15.8 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 6.3/15.8 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 6.3/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.4/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.4/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.5/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.5/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.6/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.6/15.8 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.7/15.8 MB 1.1 MB/s eta 0:00:09
   ----------------- ---------------------- 6.7/15.8 MB 1.1 MB/s eta 0:00:09
   ----------------- ---------------------- 6.8/15.8 MB 1.1 MB/s eta 0:00:09
   ----------------- ---------------------- 6.9/15.8 MB 1.1 MB/s eta 0:00:09
   ----------------- ---------------------- 6.9/15.8 MB 1.1 MB/s eta 0:00:09
   ----------------- ---------------------- 7.0/15.8 MB 1.1 MB/s eta 0:00:09
   ----------------- ---------------------- 7.1/15.8 MB 1.1 MB/s eta 0:00:09
   ------------------ --------------------- 7.1/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------ --------------------- 7.2/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------ --------------------- 7.3/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------ --------------------- 7.4/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------- -------------------- 7.5/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------- -------------------- 7.6/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------- -------------------- 7.8/15.8 MB 1.1 MB/s eta 0:00:08
   ------------------- -------------------- 7.9/15.8 MB 1.1 MB/s eta 0:00:08
   -------------------- ------------------- 8.0/15.8 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 8.1/15.8 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 8.2/15.8 MB 1.2 MB/s eta 0:00:07
   -------------------- ------------------- 8.3/15.8 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.3/15.8 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.4/15.8 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.5/15.8 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.5/15.8 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.6/15.8 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.6/15.8 MB 1.2 MB/s eta 0:00:07
   ---------------------- ----------------- 8.7/15.8 MB 1.2 MB/s eta 0:00:07
   ---------------------- ----------------- 8.8/15.8 MB 1.2 MB/s eta 0:00:07
   ---------------------- ----------------- 8.8/15.8 MB 1.2 MB/s eta 0:00:06
   ---------------------- ----------------- 8.9/15.8 MB 1.2 MB/s eta 0:00:06
   ---------------------- ----------------- 9.0/15.8 MB 1.2 MB/s eta 0:00:06
   ---------------------- ----------------- 9.1/15.8 MB 1.2 MB/s eta 0:00:06
   ----------------------- ---------------- 9.1/15.8 MB 1.2 MB/s eta 0:00:06
   ----------------------- ---------------- 9.2/15.8 MB 1.2 MB/s eta 0:00:06
   ----------------------- ---------------- 9.3/15.8 MB 1.2 MB/s eta 0:00:06
   ----------------------- ---------------- 9.3/15.8 MB 1.2 MB/s eta 0:00:06
   ----------------------- ---------------- 9.4/15.8 MB 1.2 MB/s eta 0:00:06
   ----------------------- ---------------- 9.5/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------ --------------- 9.5/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------ --------------- 9.6/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------ --------------- 9.6/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------ --------------- 9.7/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------ --------------- 9.7/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------ --------------- 9.8/15.8 MB 1.2 MB/s eta 0:00:06
   ------------------------- -------------- 9.9/15.8 MB 1.2 MB/s eta 0:00:05
   ------------------------- -------------- 9.9/15.8 MB 1.2 MB/s eta 0:00:05
   ------------------------- -------------- 10.0/15.8 MB 1.2 MB/s eta 0:00:05
   ------------------------- -------------- 10.1/15.8 MB 1.2 MB/s eta 0:00:05
   ------------------------- -------------- 10.2/15.8 MB 1.2 MB/s eta 0:00:05
   ------------------------- -------------- 10.2/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.3/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.3/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.4/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.5/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.5/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.6/15.8 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 10.6/15.8 MB 1.2 MB/s eta 0:00:05
   --------------------------- ------------ 10.7/15.8 MB 1.2 MB/s eta 0:00:05
   --------------------------- ------------ 10.8/15.8 MB 1.2 MB/s eta 0:00:05
   --------------------------- ------------ 10.8/15.8 MB 1.2 MB/s eta 0:00:05
   --------------------------- ------------ 10.9/15.8 MB 1.2 MB/s eta 0:00:05
   --------------------------- ------------ 11.0/15.8 MB 1.2 MB/s eta 0:00:05
   ---------------------------- ----------- 11.1/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.1/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.1/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.1/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.2/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.3/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.3/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.3/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.4/15.8 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 11.4/15.8 MB 1.2 MB/s eta 0:00:04
   ----------------------------- ---------- 11.5/15.8 MB 1.2 MB/s eta 0:00:04
   ----------------------------- ---------- 11.6/15.8 MB 1.2 MB/s eta 0:00:04
   ----------------------------- ---------- 11.6/15.8 MB 1.2 MB/s eta 0:00:04
   ----------------------------- ---------- 11.7/15.8 MB 1.2 MB/s eta 0:00:04
   ----------------------------- ---------- 11.7/15.8 MB 1.2 MB/s eta 0:00:04
   ----------------------------- ---------- 11.8/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 11.9/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 11.9/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 12.0/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 12.1/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 12.1/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 12.1/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------ --------- 12.2/15.8 MB 1.2 MB/s eta 0:00:04
   ------------------------------- -------- 12.2/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.3/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.3/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.4/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.4/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.5/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.6/15.8 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 12.6/15.8 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 12.7/15.8 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 12.8/15.8 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 12.8/15.8 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 12.9/15.8 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 12.9/15.8 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 13.0/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.0/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.1/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.1/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.2/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.2/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.3/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.3/15.8 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 13.4/15.8 MB 1.2 MB/s eta 0:00:03

In [3]:
import pandas as pd
import numpy as np

In [6]:
# data 폴더에 이쓴ㄴ 파일을 읽어 온다.
movie_df = pd.read_json('./data/movie.json')

In [7]:
movie_df

        id                              title
0        1                             Planes
1        2  Big Mommas: Like Father, Like Son
2        3                   Babes in Toyland
3        4             Million Dollar Mystery
4        5                       Street Kings
...    ...                                ...
1995  1997               Journey for Margaret
1996  1998                    Black Hole, The
1997  1999                    Little Fugitive
1998  2000    Monty Python and the Holy Grail
1999  2001           Loins of Punjab Presents

[2000 rows x 2 columns]

In [9]:
review_df = pd.read_json('./data/review.json')

In [12]:
review_df.drop( 'id' , axis = 1, inplace = True)

In [13]:
review_df

      movieId  userId  rating
0         863     189       4
1         608     217       3
2         405       6       2
3         959     238       5
4         839     122       3
...       ...     ...     ...
1996      816      35       4
1997       85     212       2
1998      952     273       4
1999      729     240       1
2000      878     110       3

[2001 rows x 3 columns]

In [17]:
movie_df.rename( columns= {'id' : 'movieId'}, inplace = True)

In [18]:
movie_df

      movieId                              title
0           1                             Planes
1           2  Big Mommas: Like Father, Like Son
2           3                   Babes in Toyland
3           4             Million Dollar Mystery
4           5                       Street Kings
...       ...                                ...
1995     1997               Journey for Margaret
1996     1998                    Black Hole, The
1997     1999                    Little Fugitive
1998     2000    Monty Python and the Holy Grail
1999     2001           Loins of Punjab Presents

[2000 rows x 2 columns]

In [21]:
df = pd.merge(movie_df, review_df, on = 'movieId', how='left')

In [22]:
df

      movieId                              title  userId  rating
0           1                             Planes   286.0     4.0
1           1                             Planes   286.0     4.0
2           2  Big Mommas: Like Father, Like Son   109.0     2.0
3           2  Big Mommas: Like Father, Like Son   188.0     3.0
4           2  Big Mommas: Like Father, Like Son   243.0     4.0
...       ...                                ...     ...     ...
3371     1997               Journey for Margaret     NaN     NaN
3372     1998                    Black Hole, The     NaN     NaN
3373     1999                    Little Fugitive     NaN     NaN
3374     2000    Monty Python and the Holy Grail     NaN     NaN
3375     2001           Loins of Punjab Presents     NaN     NaN

[3376 rows x 4 columns]

In [23]:
# 각 영화 제목별로, 별점에 대한 기본 통계치를 확인해 보자
df.groupby('movieId')['rating'].describe()

         count      mean       std  min   25%  50%   75%  max
movieId
1          2.0  4.000000  0.000000  4.0  4.00  4.0  4.00  4.0
2          6.0  3.000000  0.894427  2.0  2.25  3.0  3.75  4.0
3          3.0  3.666667  1.154701  3.0  3.00  3.0  4.00  5.0
4          2.0  3.000000  0.000000  3.0  3.00  3.0  3.00  3.0
5          0.0       NaN       NaN  NaN   NaN  NaN   NaN  NaN
...        ...       ...       ...  ...   ...  ...   ...  ...
1997       0.0       NaN       NaN  NaN   NaN  NaN   NaN  NaN
1998       0.0       NaN       NaN  NaN   NaN  NaN   NaN  NaN
1999       0.0       NaN       NaN  NaN   NaN  NaN   NaN  NaN
2000       0.0       NaN       NaN  NaN   NaN  NaN   NaN  NaN
2001       0.0       NaN       NaN  NaN   NaN  NaN   NaN  NaN

[2000 rows x 8 columns]

In [24]:
df.groupby('title')['rating'].describe()

,count,mean,std,min,25%,50%,75%,max
title,,,,,,,,
"1, 2, 3, Sun (Un, deuz, trois, soleil)",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112 Weddings,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Storeys (Shier lou),6.0,4.333333,1.032796,3.0,3.5,5.0,5.00,5.0
13 Ghosts,2.0,3.000000,0.000000,3.0,3.0,3.0,3.00,3.0
2019: After the Fall of New York,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
"Young Black Stallion, The",6.0,4.333333,0.516398,4.0,4.0,4.0,4.75,5.0
Zombie (a.k.a. Zombie 2: The Dead Are Among U,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zombies of the Stratosphere,2.0,3.000000,0.000000,3.0,3.0,3.0,3.00,3.0
Zone 39,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zulu Dawn,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df

      movieId                              title  userId  rating
0           1                             Planes   286.0     4.0
1           1                             Planes   286.0     4.0
2           2  Big Mommas: Like Father, Like Son   109.0     2.0
3           2  Big Mommas: Like Father, Like Son   188.0     3.0
4           2  Big Mommas: Like Father, Like Son   243.0     4.0
...       ...                                ...     ...     ...
3371     1997               Journey for Margaret     NaN     NaN
3372     1998                    Black Hole, The     NaN     NaN
3373     1999                    Little Fugitive     NaN     NaN
3374     2000    Monty Python and the Holy Grail     NaN     NaN
3375     2001           Loins of Punjab Presents     NaN     NaN

[3376 rows x 4 columns]

In [ ]:
df.corr(numeric_only= True)

In [ ]:
# 영화 제목이 모두 컬럼으로 가있어야지 상관계수를 뽑을 수 있다
# 왜왜. corr() 함수는 컬럼과 컬럼의 관계를 뽑아주니까

In [28]:
review_df['userId'].nunique()

294

In [29]:
df

      movieId                              title  userId  rating
0           1                             Planes   286.0     4.0
1           1                             Planes   286.0     4.0
2           2  Big Mommas: Like Father, Like Son   109.0     2.0
3           2  Big Mommas: Like Father, Like Son   188.0     3.0
4           2  Big Mommas: Like Father, Like Son   243.0     4.0
...       ...                                ...     ...     ...
3371     1997               Journey for Margaret     NaN     NaN
3372     1998                    Black Hole, The     NaN     NaN
3373     1999                    Little Fugitive     NaN     NaN
3374     2000    Monty Python and the Holy Grail     NaN     NaN
3375     2001           Loins of Punjab Presents     NaN     NaN

[3376 rows x 4 columns]

In [32]:
df_all = df.pivot_table(index= 'userId', columns= 'title', values= 'rating', aggfunc= 'mean')

In [41]:
## 샘플 데이터에는 리뷰가 많아야 3개 정도라서 정확도가 떨어질수밖에 없다.
## 별점의 갯수가 특정 갯수 이하인 것은 상관분석에서 뺼 수 있다
## 반대로 말하면 별점의 객수가 특정갯수 이상인것만 유의미한 상관계수를 뽑도록 할 수 있다

corr_movie = df_all.corr(min_periods= 2)

In [ ]:
## 개인 맞춤형 영화 추천을 해야 하므로,
## 로그인 한 사람의 리뷰 정보를 기반으로해서 추천을 해줘야 한다.

In [44]:
corr_movie

title,12 Storeys (Shier lou),13 Ghosts,21 Hours at Munich,30 Days of Night,33 Postcards,"4 Months, 3 Weeks and 2 Days (4 luni, 3 sapta",71 Fragments of a Chronology of Chance (71 Fr,7500,8MM,A Magnificent Haunting,...,Woodstock,Wrongfully Accused,Xtro 2: The Second Encounter,Yanks,"Year and a Half in the Life of Metallica, A",You've Got Mail,Young Adult,Young Bess,"Young Black Stallion, The",Zombies of the Stratosphere
title,,,,,,,,,,,,,,,,,,,,,
12 Storeys (Shier lou),1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13 Ghosts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21 Hours at Munich,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30 Days of Night,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33 Postcards,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You've Got Mail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Young Adult,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Young Bess,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Young Black Stallion, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Zombies of the Stratosphere,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
my_rating = pd.read_json('./data/my_rating.json')

In [46]:
my_rating

                                         title  rating
0         Silver Stallion (Silver Brumpy, The)       4
1                             There Be Dragons       3
2                                Hireling, The       3
3  I Have Found It (Kandukondain Kandukondain)       3
4         Silver Stallion (Silver Brumpy, The)       4
5                             There Be Dragons       3
6                                Hireling, The       3
7  I Have Found It (Kandukondain Kandukondain)       3

In [48]:
title = my_rating['title'][0]

In [49]:
title

'Silver Stallion (Silver Brumpy, The)'

In [53]:
corr_movie[title].dropna()

Series([], Name: Silver Stallion (Silver Brumpy, The), dtype: float64)

In [97]:
movie_df = pd.read_csv('./data/Movie_Id_Titles.csv')

In [98]:
review_df = pd.read_csv('./data/user_rating.csv')

In [99]:
df = pd.merge(movie_df, review_df, on ='item_id', how='left')

In [100]:
df

,item_id,title,user_id,rating,timestamp
0,1,Toy Story (1995),308,4,887736532
1,1,Toy Story (1995),287,5,875334088
2,1,Toy Story (1995),148,4,877019411
3,1,Toy Story (1995),280,4,891700426
4,1,Toy Story (1995),66,3,883601324
...,...,...,...,...,...
99998,1678,Mat' i syn (1997),863,1,889289570
99999,1679,B. Monkey (1998),863,3,889289491
100000,1680,Sliding Doors (1998),863,2,889289570
100001,1681,You So Crazy (1994),896,3,887160722
100002,1682,Scream of Stone (Schrei aus Stein) (1991),916,3,880845755

In [101]:
df_all = df.pivot_table(index= 'user_id', columns = 'title', values='rating', aggfunc= 'mean' )

In [102]:
corr_movie = df_all.corr(min_periods= 50)

In [103]:
corr_movie

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1-900 (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101 Dalmatians (1996),NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Angry Men (1957),NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.178848,NaN,NaN,...,NaN,NaN,NaN,0.096546,NaN,NaN,NaN,NaN,NaN,NaN
187 (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Young Guns II (1990),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Young Poisoner's Handbook, The (1995)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zeus and Roxanne (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Á köldum klaka (Cold Fever) (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
my_rating = pd.read_csv('./data/My_Ratings.csv')

In [105]:
my_rating

                     Movie Name  Ratings
0         101 Dalmatians (1996)        5
1  2001: A Space Odyssey (1968)        4
2           You So Crazy (1994)        1

In [106]:
title = my_rating['Movie Name'][0]

In [107]:
title

'101 Dalmatians (1996)'

In [108]:
recom_movie = corr_movie[title].dropna().sort_values(ascending=False).to_frame()

In [109]:
recom_movie.columns = ['corr']

In [110]:
recom_movie['weight'] = recom_movie['corr'] * my_rating['Ratings'][0]

In [111]:
recom_movie

                                         corr    weight
title
101 Dalmatians (1996)                1.000000  5.000000
Top Gun (1986)                       0.492492  2.462461
Hunt for Red October, The (1990)     0.483807  2.419033
Liar Liar (1997)                     0.469765  2.348824
Grumpier Old Men (1995)              0.461647  2.308235
...                                       ...       ...
Star Trek: The Wrath of Khan (1982) -0.115497 -0.577487
Groundhog Day (1993)                -0.126499 -0.632497
Twelve Monkeys (1995)               -0.184141 -0.920703
Alien (1979)                        -0.190265 -0.951326
Fargo (1996)                        -0.245368 -1.226842

[76 rows x 2 columns]

In [112]:
# 비어있는 데이터 프레임 만들고, 
# 내가 본 영화의 가중치까지 계산해서, 추천영화를 뽑아내자
# 추천 영화들을 비어있는 데이터 프레임에 추가하면 된다

In [113]:
movie_list = pd.DataFrame()

for i in range( my_rating.shape[0] ) :
    title = my_rating['Movie Name'][i]
    recom_movie = corr_movie[title].dropna().sort_values(ascending=False).to_frame()
    recom_movie.columns = ['corr']
    recom_movie['weight'] = recom_movie['corr'] * my_rating['Ratings'][i]
    movie_list = pd.concat( [movie_list, recom_movie] )

In [114]:
movie_list.sort_values('weight', ascending=False, inplace=True)

In [115]:
movie_list

                                         corr    weight
title
101 Dalmatians (1996)                1.000000  5.000000
2001: A Space Odyssey (1968)         1.000000  4.000000
Top Gun (1986)                       0.492492  2.462461
Hunt for Red October, The (1990)     0.483807  2.419033
Liar Liar (1997)                     0.469765  2.348824
...                                       ...       ...
Sword in the Stone, The (1963)      -0.238260 -0.953042
Jungle Book, The (1994)             -0.264809 -1.059235
So I Married an Axe Murderer (1993) -0.276184 -1.104736
Air Force One (1997)                -0.282994 -1.131976
Fargo (1996)                        -0.245368 -1.226842

[434 rows x 2 columns]

In [116]:
# 내가 이미 본 영화는 추천에서 제외한다. 
for title in my_rating['Movie Name'] :
    if title in movie_list.index :
        movie_list.drop(title, axis = 0, inplace=True)

In [117]:
# 이 리스트에는 중복된 영화도 있을 수 있다
# 따라서 중복된 영화가 있으면 웨이트 점수가 높은것으로만
# 나오도록 한다

In [123]:
movie_list = movie_list.groupby('title')['weight'].max().sort_values(ascending = False).head(10)

In [128]:
movie_list.to_frame().reset_index().to_dict('records')

[{'title': 'Top Gun (1986)', 'weight': 2.4624611027070586},
 {'title': 'Hunt for Red October, The (1990)', 'weight': 2.4190326101711372},
 {'title': 'Liar Liar (1997)', 'weight': 2.3488243471288577},
 {'title': 'Grumpier Old Men (1995)', 'weight': 2.3082353839359935},
 {'title': 'Lion King, The (1994)', 'weight': 2.1328639519572254},
 {'title': 'Dragonheart (1996)', 'weight': 2.068932722556984},
 {'title': 'Aladdin (1992)', 'weight': 1.9255875243143343},
 {'title': 'Rock, The (1996)', 'weight': 1.914278749450704},
 {'title': 'Father of the Bride Part II (1995)', 'weight': 1.8395838326642335},
 {'title': 'True Romance (1993)', 'weight': 1.8367567728189418}]

In [122]:
corr_movie.to_csv('corr_movie.csv')